on:
  release:
    types: [published, edited, released]
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:      
      - name: Trigger Repo Update
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: new-release
