on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    name : releasePlz
    if : ${{ startsWith(github.event.head_commit.message, 'chore:') }}
    runs-on: ubuntu-latest
    steps:
      - id: rp
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
